apiVersion: v1
kind: Pod
metadata:
  name: debian1
spec:
  containers:
  - image: debian:latest
    name: debian
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    securityContext:
      capabilities:
        add: ["NET_RAW"]
