---
- hosts: all
  pre_tasks:
    - name: Install iptables-legacy
      apt:
        name: ['arptables','ebtables','iptables']
        update_cache: yes
        state: present
    - name: Install GPG
      apt:
        name: gnupg
        update_cache: yes
        state: present
    - name: Move iptables alternatives to legacy (calico issue)
      community.general.alternatives:
        name: "{{ item }}"
        path: "/usr/sbin/{{ item }}-legacy"
      with_items:
        - iptables
        - ip6tables
        - arptables
        - ebtables
    - name: Load br_netfilter
      community.general.modprobe:
        name: br_netfilter
        state: present
    - name: Set ip_forward_v4 in /etc/sysctl.d/k8s-net-forward.conf
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/k8s-net-forward.conf
      with_items:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding
    - name: Set bridge-nf-call-ip6tables in /etc/sysctl.d/k8s-br.conf
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/k8s-br.conf
      with_items:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
    - name: Disable swap in fstab
      replace:
        path: /etc/fstab
        regexp: '(^\s*[^#].*swap)'
        replace: '#\1'
    - name: Run swapoff
      shell: swapoff -a
  tasks:
    - name: Install crio
      include_role:
        name: crio-install
    - name: Install kubeadm
      include_role:
        name: kubeadm-install
- hosts: control-plane
  tasks:
    - name: Install NFS Server
      include_role:
        name: nfs-server
    - name: Configure control plane
      include_role:
        name: kubeadm-init
- hosts: compute
  tasks:
    - name: Install NFS Client
      include_role:
        name: nfs-client
    - name: Join nodes
      include_role:
        name: kubeadm-join
