---
- hosts: all
  pre_tasks:
    - name: Load br_netfilter
      community.general.modprobe:
        name: br_netfilter
        state: present
    - name: Install arptables
      apt:
        name: arptables
        update_cache: yes
        state: present
    - name: Set ip_forward_v4 in /etc/sysctl.d/k8s-net-forward.conf
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/k8s-net-forward.conf
      with_items:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding
    - name: Set bridge-nf-call-ip6tables in /etc/sysctl.d/k8s-br.conf
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/k8s-br.conf
      with_items:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
    - name: Disable swap in fstab
      replace:
        path: /etc/fstab
        regexp: '(^\s*[^#].*swap)'
        replace: '#\1'
    - name: Run swapoff
      shell: swapoff -a
  tasks:
    - name: Install crio
      include_role:
        name: crio-install
    - name: Install kubeadm
      include_role:
        name: kubeadm-install

- hosts: control-plane
  tasks:
    - name: Configure control plane
      include_role:
        name: kubeadm-init

- hosts: compute
  tasks:
    - name: Join nodes
      include_role:
        name: kubeadm-join
