---
all:
  children:
    control-plane:
      hosts:
        api-server.lab.local:
    compute:
      hosts:
        node[1:2].lab.local:
  vars:
    crio_version: "1.20"
    linux_version: Debian_10
    debian_release: buster
    calico_version: v3.17
    kubernetes_version: "1.20.2-00"
    nico_uid: "2010"
