---
all:
  children:
    control-plane:
      hosts:
        admin.lab.local:
    compute:
      hosts:
        node[1:2].lab.local:
  vars:
    crio_version: "1.22"
    linux_version: Debian_11
    debian_release: bullseye
    calico_version: v3.21
    kubernetes_version: "1.22.3-00"
    nico_uid: "2010"
