---
- name: Intializing Kubernetes Cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket="unix:///var/run/crio/crio.sock"
- pause: seconds=30
- name: Create directory for kube config
  file: 
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Copy /etc/kubernetes/admin.conf to user home directory /home/root/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
- pause: seconds=10
- name: Remove the cache directory
  file: 
    path: /root/.kube/cache
    state: absent
- name: Install calico
  command: "kubectl apply -f https://docs.projectcalico.org/{{ calico_version }}/manifests/calico.yaml"
- pause: seconds=30
- name: Get the token for joining the nodes with Kuberentes master
  shell: kubeadm token create --print-join-command
  register: kubernetes_join_command
- debug:
    msg: "{{ kubernetes_join_command.stdout }}"
- name: Copy join command to local file
  become: false
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="kubernetes_join_command" mode=0555
- name: Configure kubectl command auto-completion.
  lineinfile:
    dest: /root/.bashrc
    line: 'source <(kubectl completion bash)'
    insertafter: EOF
#- name: Enable pods scheduling on all nodes
#  command: "kubectl taint nodes --all node-role.kubernetes.io/master-"
#- name: Taint the control-plane to dedicate it to slurmctld affinity pods
#  command: "kubectl taint nodes {{ ansible_hostname }} dedicated=slurmctld:NoSchedule"
- name: Add Docker private repo
  command: "kubectl create secret docker-registry regcred --docker-server=docker.io --docker-username=nyk0 --docker-password=docyp@SS! --docker-email=nicolas.greneche@gmail.com"
