---
- name: Load overlay module
  community.general.modprobe:
    name: overlay
    state: present
- name: Write in /etc/modules
  lineinfile:
    line: overlay
    state: present
    path: /etc/modules
- name: Install cri-o dependencies
  apt:
    name: make
    state: present
    update_cache: yes
- name: Get crio
  unarchive:
    src: "https://storage.googleapis.com/k8s-conform-cri-o/artifacts/crio-{{ crio_version }}.tar.gz"
    dest: /tmp/
    remote_src: yes
- name: Install crio
  shell:
    chdir: "/tmp/crio-{{ crio_version }}"
    cmd: make install
- name: Update /etc/containers/registries.conf
  copy:
    src: registries.conf
    dest: /etc/containers/registries.conf
- name: Start crio
  systemd:
    name: crio
    daemon_reload: yes
    enabled: yes
    state: started
